name: Test Docker Compose (Develop)

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test-compose:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and start services with Docker Compose
        run: |
          cd docker
          docker compose -f docker-compose.dev.yml up -d --build

      - name: Wait for services to be ready
        run: |
          echo "⏳ Esperando que los servicios estén listos (esto puede tomar ~8 minutos)..."
          
          cd docker
          for i in {1..48}; do
            echo "Esperando... $((i * 10)) segundos transcurridos"
            sleep 10
          
            RUNNING=$(docker compose -f docker-compose.dev.yml ps -q | wc -l)
            if [ $RUNNING -eq 4 ]; then
              HEALTHY=$(docker compose -f docker-compose.dev.yml ps | grep -E "agorasoft-(database|backend|frontend|proxy)" | grep -c "Up")
              if [ $HEALTHY -eq 4 ]; then
                echo "✅ Todos los servicios están listos después de $((i * 10)) segundos"
                break
              fi
            fi
          done

      - name: Check running containers
        run: |
          echo "📋 Estado de los contenedores:"
          cd docker
          docker compose -f docker-compose.dev.yml ps
          echo ""
          echo "📝 Logs de los servicios:"
          docker compose -f docker-compose.dev.yml logs --tail=50

      - name: Verify specific services are running
        run: |
          echo "🔍 Verificando servicios específicos..."
          
          if docker ps --filter "name=agorasoft-database" --filter "status=running" | grep -q agorasoft-database; then
            echo "✅ agorasoft-database está corriendo"
          else
            echo "❌ agorasoft-database NO está corriendo"
            docker logs agorasoft-database
            exit 1
          fi
          
          if docker ps --filter "name=agorasoft-backend" --filter "status=running" | grep -q agorasoft-backend; then
            echo "✅ agorasoft-backend está corriendo"
          else
            echo "❌ agorasoft-backend NO está corriendo"
            docker logs agorasoft-backend
            exit 1
          fi
          
          if docker ps --filter "name=agorasoft-frontend" --filter "status=running" | grep -q agorasoft-frontend; then
            echo "✅ agorasoft-frontend está corriendo"
          else
            echo "❌ agorasoft-frontend NO está corriendo"
            docker logs agorasoft-frontend
            exit 1
          fi
          
          if docker ps --filter "name=agorasoft-proxy" --filter "status=running" | grep -q agorasoft-proxy; then
            echo "✅ agorasoft-proxy está corriendo"
          else
            echo "❌ agorasoft-proxy NO está corriendo"
            docker logs agorasoft-proxy
            exit 1
          fi
          
          echo ""
          echo "🎉 Todos los servicios (database, backend, frontend, proxy) están corriendo correctamente"

      - name: Verify database health
        run: |
          echo "🏥 Verificando salud de la base de datos..."
          docker exec agorasoft-database pg_isready -U postgres -d AgoraSoft
          
          echo ""
          echo "📊 Verificando que el schema inventario existe..."
          docker exec agorasoft-database psql -U postgres -d AgoraSoft -c "\dn inventario"
          
          echo ""
          echo "📋 Verificando que la tabla usuario existe..."
          docker exec agorasoft-database psql -U postgres -d AgoraSoft -c "\dt inventario.usuario"

      - name: Login to GitHub Container Registry
        if: github.event_name == 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Get latest version and increment
        if: github.event_name == 'pull_request'
        id: version
        run: |
          echo "🔍 Buscando última versión en GHCR..."
          
          LAST_VERSION=$(curl -s -H "Authorization: Bearer ${{ secrets.GHCR_TOKEN }}" \
            "https://api.github.com/orgs/arquitecturasoftware-imagicode/packages/container/agorasoft-backend/versions" \
            | jq -r '.[0].metadata.container.tags[] | select(test("^[0-9]+\\.[0-9]+\\.[0-9]+$"))' \
            | sort -V | tail -n1)
          
          if [ -z "$LAST_VERSION" ]; then
            echo "⚠️  No se encontró versión previa, comenzando en 1.0.0"
            NEW_VERSION="1.0.0"
          else
            echo "📌 Última versión encontrada: $LAST_VERSION"
            IFS='.' read -r MAJOR MINOR PATCH <<< "$LAST_VERSION"
            PATCH=$((PATCH + 1))
            NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          fi
          
          echo "🆕 Nueva versión: $NEW_VERSION"
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: List Docker images (debug)
        if: github.event_name == 'pull_request'
        run: |
          echo "🔍 Listando todas las imágenes Docker disponibles:"
          docker images
          echo ""
          echo "🔍 Buscando imágenes de backend:"
          docker images | grep -i backend || echo "No se encontraron imágenes de backend"
          echo ""
          echo "🔍 Buscando imágenes de frontend:"
          docker images | grep -i frontend || echo "No se encontraron imágenes de frontend"

      - name: Tag and push images to GHCR
        if: github.event_name == 'pull_request'
        env:
          VERSION: ${{ steps.version.outputs.version }}
        run: |
          echo "🏷️  Etiquetando imágenes con versión: $VERSION"
          
          # Buscar las imágenes construidas (búsqueda más flexible)
          BACKEND_IMAGE=$(docker images --format "{{.Repository}}:{{.Tag}}" | grep -i backend | grep -v ghcr.io | head -n1)
          FRONTEND_IMAGE=$(docker images --format "{{.Repository}}:{{.Tag}}" | grep -i frontend | grep -v ghcr.io | head -n1)
          
          if [ -z "$BACKEND_IMAGE" ]; then
            echo "❌ No se encontró imagen de backend"
            exit 1
          fi
          
          if [ -z "$FRONTEND_IMAGE" ]; then
            echo "❌ No se encontró imagen de frontend"
            exit 1
          fi
          
          echo "✅ Backend image encontrada: $BACKEND_IMAGE"
          echo "✅ Frontend image encontrada: $FRONTEND_IMAGE"
          
          # Tag backend
          docker tag $BACKEND_IMAGE ghcr.io/arquitecturasoftware-imagicode/agorasoft-backend:$VERSION
          docker tag $BACKEND_IMAGE ghcr.io/arquitecturasoftware-imagicode/agorasoft-backend:latest
          
          # Tag frontend
          docker tag $FRONTEND_IMAGE ghcr.io/arquitecturasoftware-imagicode/agorasoft-frontend:$VERSION
          docker tag $FRONTEND_IMAGE ghcr.io/arquitecturasoftware-imagicode/agorasoft-frontend:latest
          
          echo "📤 Subiendo imágenes a GHCR..."
          
          # Push backend
          docker push ghcr.io/arquitecturasoftware-imagicode/agorasoft-backend:$VERSION
          docker push ghcr.io/arquitecturasoftware-imagicode/agorasoft-backend:latest
          
          # Push frontend
          docker push ghcr.io/arquitecturasoftware-imagicode/agorasoft-frontend:$VERSION
          docker push ghcr.io/arquitecturasoftware-imagicode/agorasoft-frontend:latest
          
          echo "✅ Imágenes subidas exitosamente:"
          echo "   - ghcr.io/arquitecturasoftware-imagicode/agorasoft-backend:$VERSION"
          echo "   - ghcr.io/arquitecturasoftware-imagicode/agorasoft-backend:latest"
          echo "   - ghcr.io/arquitecturasoftware-imagicode/agorasoft-frontend:$VERSION"
          echo "   - ghcr.io/arquitecturasoftware-imagicode/agorasoft-frontend:latest"

      - name: Show logs on failure
        if: failure()
        run: |
          echo "❌ El workflow falló. Mostrando logs completos:"
          cd docker
          docker compose -f docker-compose.dev.yml logs

      - name: Stop and remove containers
        if: always()
        run: |
          echo "🧹 Limpiando contenedores..."
          cd docker
          docker compose -f docker-compose.dev.yml down -v